export const USER = 'me'
export const INVALID_TOKEN = 'Invalid token'
export const INVALID_SESSION = 'Invalid session'
export const MIME_TYPE_NO_INLINE = 'application/octet-stream'
export const ARCHIVE_LABEL = 'ARCHIVE'
